### ISSUE TITLE
是否可以多分类

### ISSUE THREAD

**Issue by buthi** [autoliuweijie/K-BERT#79]
您好，我正在复现您的代码，请问对文本分类任务是只能实现二分类还是可以实现多分类呢。我用自己的多类数据训练时报错：
Traceback (most recent call last):
  File "run_kbert_cls.py", line 578, in <module>
    main()
  File "run_kbert_cls.py", line 557, in main
    result = evaluate(args, False)
  File "run_kbert_cls.py", line 393, in evaluate
    print("Acc. (Correct/Total): {:.4f} ({}/{}) ".format(correct/len(dataset), correct, len(dataset)))
ZeroDivisionError: division by zero

**Comment by buthi** [comment]
已解决 刚开始没仔细看

**Comment by 000163** [comment]
> 已解决 刚开始没仔细看

請問您後來能使用多分類任務嗎

**Comment by buthi** [comment]
> > 已解决 刚开始没仔细看
> 
> 請問您後來能使用多分類任務嗎

可以

**Comment by SamIp523** [comment]
您好，不知道是否可以请教您是修改哪一部分以实现多分类呢？
